sudo: required
services:
  - docker

before_install:
  - docker build -t thaugen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thaugen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-085309336975"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
