# language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t thaugen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thaugen/docker-react npm run test
